[tool.poetry]
name = "slurmray"
version = "1.0.0"
description = "A tool to easily launch calculations from python notebooks using the resources of a SLURM cluster"
authors = ["Henri Jamet <henri.jamet@unil.ch>"]
license = "Apache License"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.9.13"
dill = "^0.3.7"
ray = {extras = ["data", "serve", "train", "tune"], version = "^2.7.1"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
